### ISSUE TITLE
TalkTorial 1 - T1_ChEMBL - Step 24

### ISSUE THREAD

**Issue by Farabotti** [volkamerlab/TeachOpenCADD#15] opened 2020-01-13 16:45 UTC
Dear all,

being a new user I am struggling in some of the steps of this amazing Talktorial.
At the step 24, I do not manage to proceed to transform my "smile" structures in formula within the template. 
`PandasTools.AddMoleculeColumnToFrame(output_df, smilesCol='smiles') `
Any suggestion?
Thanks

**Comment by jaimergp** [comment] 2020-01-14 10:48
Hi! Can you provide some more information about the error? Is there any traceback you can paste here or just a silent/wrong result? Thanks!

**Comment by Farabotti** [comment] 2020-01-14 16:47
Hi, I will try to explain myself:
the really first line would be:
`from chembl_webresource_client.new_client import new_client
import pandas as pd
import math
from rdkit.Chem import PandasTools`

but when I try to enter it I receive:
`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-54c833032a72> in <module>
      2 import pandas as pd
      3 import math
----> 4 from rdkit.Chem import PandasTools

ModuleNotFoundError: No module named 'rdkit'`

So I used:
`pip install chembl_webresource_client`

and it worked but when I tried to enter line 24:
`PandasTools.AddMoleculeColumnToFrame(output_df, smilesCol='smiles')`

I get:

`---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-767d415f36ea> in <module>
----> 1 PandasTools.AddMoleculeColumnToFrame(output_df, smilesCol='smiles')

NameError: name 'PandasTools' is not defined
`

I hope this is the correct way to write everything.
Thanks a lot!

**Comment by jaimergp** [comment] 2020-01-14 17:15
Have you created a `conda` environment with the dependencies specified [in this file](https://github.com/volkamerlab/TeachOpenCADD/blob/master/environment.yml)? That should take care of all the missing packages. More instructions can be found [here](https://github.com/volkamerlab/TeachOpenCADD#install-locally-for-all-talktorials).

**Comment by Farabotti** [comment] 2020-01-14 19:07
I am actually working on Anaconda 3 on a mac. Shouldn't the CONDA env be already installed?
Thanks and sorry again for the very easy-level questions.

**Comment by jaimergp** [comment] 2020-01-14 20:03
Anaconda will provide a default environment with the installation (called `base`), but you can create more with `conda env create`! The purpose of having multiple environments is the possibility of isolating dependencies and providing reproducible configurations. In our project, we provide a file `environment.yml` with the exact dependencies so you can use our notebooks without the kind of problems you are observing.

Let me know if there's anything else I can clarify!

**Comment by amitindore** [comment] 2020-05-29 10:50
can i use these material and coding as such for an online course I am designing for pharmacy students ?

**Comment by jaimergp** [comment] 2020-05-29 14:15
Hi @amitindore!

Please refer to the [`LICENSE`](https://github.com/volkamerlab/TeachOpenCADD/blob/master/LICENSE) to check whether the covered scenarios fit your case. 

I am also tagging @AndreaVolkamer and @dominiquesydow in case they want to clarify further.

**Comment by dominiquesydow** [comment] 2020-06-02 09:08
Hi @amitindore, 

Thank you very much for your interest in TeachOpenCADD!

You are most welcome to use and adapt the material. When doing so please

- [cite](https://github.com/volkamerlab/TeachOpenCADD/blob/master/README.md#citation) the TeachOpenCADD publication as well as link the repo and
- grant the same or more permissive license to your material,

as pointed out by @jaimergp ([`LICENSE`](https://github.com/volkamerlab/TeachOpenCADD/blob/master/LICENSE)).

Also, we would be happy if you and your students would [star](https://help.github.com/en/github/getting-started-with-github/saving-repositories-with-stars) those repositories they consider useful for their learning activities during your course. 

Thanks a lot and good luck with your course!

**Comment by amitindore** [comment] 2020-06-03 10:34
Thanks a lot.
This is nice gestures of yours.
Would you be comfortable if we host a webinar of yours for entire pharma
fraternity of India, on this topic?

**Comment by dominiquesydow** [comment] 2020-06-11 09:07
Hi @amitindore, 

My sincere apologies for my belated reply, it slipped my mind.

We ourselves cannot participate in such a seminar due to time constraints (in case you were also asking this), but you are absolutely welcome to use the TeachOpenCADD material for your seminar, complying with the license as discussed before.

We would be happy to hear about your experience from the course! Good luck!

**Comment by amitindore** [comment] 2020-06-12 05:25
No, no.
I am requesting you to deliver a seminar as per your convenience on this
open tutorial.
Meanwhile I would let you know that lot many images and infographics I have
taken as such from your TeachopenCADD with full acknowledgement in my free
online certificate course on AI and Drug Discovery. Once again I am
thankful to you.
Thanks.

**Comment by AndreaVolkamer** [comment] 2020-06-12 14:32
Hi @amitindore,
as my colleagues already stated, we can not offer such a seminar. 
We provide the material here as an open resource meant to be used for self-study or your own class room training.
Happy to hear that the material was useful in your course and thanks for the acknowledgement.

**Comment by amitindore** [comment] 2020-06-13 04:36
Okay sir.
Thanks.

**Comment by dominiquesydow** [comment] 2020-06-13 07:37
I am closing this issue, since both questions - the initial issue on an installation problem and the second question on licenses - are answered.

@Farabotti, feel free to reopen this issue in case you still have installation problems. 
We are currently working on a TeachOpenCADD package, which should make installing the resource much more convenient! We'll keep you posted.

@amitindore, I wish you all the best with your course!

For more license/usage (or any other) questions, please open a separate issue. Thank you!

**Closed by dominiquesydow** 2020-06-13 07:37 UTC
