### ISSUE TITLE
T008: Cannot download PDB structure via MMTF API anymore

### ISSUE THREAD

**Issue by seymasoyler** [volkamerlab/TeachOpenCADD#420] opened 2024-08-05 09:49 UTC
Hello,
Received url error when writing code to download PDB data. All the codes that needed to be written before were written and all the codes worked. I would appreciate it if you could help me on how to fix the error.

#Download PDB structures
structures=[Structure.from_pdbid(pdb_id) for pdb_id in pairs]
structures

![Error](https://github.com/user-attachments/assets/12a5aba3-2685-49f7-9064-d69116658af9)

![Screenshot from 2024-08-06 11-52-20](https://github.com/user-attachments/assets/e3109dac-c6d7-4f8c-bd2b-23c9639d738f)

**Comment by dominiquesydow** [comment] 2024-08-06 15:06
Hi @seymasoyler, 

Many thanks, the webservice used behind the scenes to download the PDB structure is not in service anymore. See more details https://github.com/volkamerlab/teachopencadd/issues/419.

We will close this issue here as a duplicate of https://github.com/volkamerlab/teachopencadd/issues/419 and add updates there instead. Thanks!

**Closed as completed** 2024-08-06 15:18 UTC

**Comment by seymasoyler** [comment] 2024-08-07 10:14
Hi @dominiquesydow,

Thanks a lot for your feedback and help.
