### ISSUE TITLE
T008: Too many requests under windows

### ISSUE THREAD

**Issue by schallerdavid** [volkamerlab/teachopencadd#231] opened 2022-04-26 05:12 UTC
It has been hard for quite some time to get the CI passing for T008 under windows. The biotite rcsb requests in cell 5 and below very often resulted in "Too many requests errors". Often it is enough to just restart the workflow under windows, but this is getting a little tedious every week. I tried adding some sleep time but this does not improve (#229). Maybe there is also a way to use the redo decorator on this? For now, I will exclude T008 from testing under windows (#230). It would be great if someone has time to take a look at this.

**Comment by dominiquesydow** [comment] 2022-08-01 13:48
I think this is a duplicate of https://github.com/volkamerlab/teachopencadd/issues/199, so I am closing this issue - but we still have this on the radar. 

Just to note, I think the request errors have been less frequent lately but still adding the `redo` decorator is a good idea.

**Closed by dominiquesydow** 2022-08-01 13:48 UTC
